USE [banco_erp]
GO

/****** Object:  Table [dbo].[COMPRA]    Script Date: 14/11/2023 21:17:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COMPRA](
	[id_compra] [int] NOT NULL,
	[datas] [date] NULL,
	[id_insumo] [int] NOT NULL,
	[valor] [float] NULL,
	[id_usuario] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id_compra] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[INSUMO]    Script Date: 14/11/2023 21:17:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[INSUMO](
	[id_insumo] [int] NOT NULL,
	[unidade_medida] [text] NULL,
	[valor] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[id_insumo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

/****** Object:  Table [dbo].[PRODUTO]    Script Date: 14/11/2023 21:17:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRODUTO](
	[id_produto] [int] NOT NULL,
	[unidade_medida] [text] NULL,
	[valor] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[id_produto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

/****** Object:  Table [dbo].[USUARIO]    Script Date: 14/11/2023 21:17:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USUARIO](
	[id_usuario] [int] NOT NULL,
	[nome] [text] NULL,
	[email] [text] NULL,
PRIMARY KEY CLUSTERED 
(
	[id_usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

/****** Object:  Table [dbo].[VENDA]    Script Date: 14/11/2023 21:17:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[VENDA](
	[id_venda] [int] NOT NULL,
	[datas] [date] NULL,
	[id_produto] [int] NOT NULL,
	[valor] [float] NULL,
	[id_usuario] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id_venda] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[COMPRA]  WITH CHECK ADD  CONSTRAINT [FK_COMPRA_INSUMO] FOREIGN KEY([id_insumo])
REFERENCES [dbo].[INSUMO] ([id_insumo])
GO

ALTER TABLE [dbo].[COMPRA] CHECK CONSTRAINT [FK_COMPRA_INSUMO]
GO

ALTER TABLE [dbo].[COMPRA]  WITH CHECK ADD  CONSTRAINT [FK_COMPRA_USUARIO] FOREIGN KEY([id_usuario])
REFERENCES [dbo].[USUARIO] ([id_usuario])
GO

ALTER TABLE [dbo].[COMPRA] CHECK CONSTRAINT [FK_COMPRA_USUARIO]
GO

ALTER TABLE [dbo].[VENDA]  WITH CHECK ADD  CONSTRAINT [FK_VENDA_PRODUTO] FOREIGN KEY([id_produto])
REFERENCES [dbo].[PRODUTO] ([id_produto])
GO

ALTER TABLE [dbo].[VENDA] CHECK CONSTRAINT [FK_VENDA_PRODUTO]
GO

ALTER TABLE [dbo].[VENDA]  WITH CHECK ADD  CONSTRAINT [FK_VENDA_USUARIO] FOREIGN KEY([id_usuario])
REFERENCES [dbo].[USUARIO] ([id_usuario])
GO

ALTER TABLE [dbo].[VENDA] CHECK CONSTRAINT [FK_VENDA_USUARIO]
GO


